### ISSUE TITLE
Import statement raises an error

### ISSUE THREAD

**Issue by Sergey-S-Lebedev** [marcus-santos/spotware_connect#1]
Hi there
just import statement
import spotware_connect as sc
raises an error

:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'pyasn1''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/spotware_connect/__init__.py", line 9, in <module>
    from .client import Client  # noqa
  File "/snap/pycharm-community/211/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_monkey_qt.py", line 114, in patched_import
    return original_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spotware_connect/client.py", line 5, in <module>
    from .protocol import Protocol
  File "/snap/pycharm-community/211/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_monkey_qt.py", line 114, in patched_import
    return original_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spotware_connect/protocol.py", line 5, in <module>
    from .messages.OpenApiCommonMessages_pb2 \
  File "/snap/pycharm-community/211/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_monkey_qt.py", line 114, in patched_import
    return original_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spotware_connect/messages/OpenApiCommonMessages_pb2.py", line 16, in <module>
    import OpenApiCommonModelMessages_pb2 as OpenApiCommonModelMessages__pb2
  File "/snap/pycharm-community/211/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_monkey_qt.py", line 114, in patched_import
    return original_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spotware_connect/messages/OpenApiCommonModelMessages_pb2.py", line 24, in <module>
    serialized_pb=_b('\n OpenApiCommonModelMessages.proto*I\n\x10ProtoPayloadType\x12\x11\n\rPROTO_MESSAGE\x10\x05\x12\r\n\tERROR_RES\x10\x32\x12\x13\n\x0fHEARTBEAT_EVENT\x10\x33*\xf0\x01\n\x0eProtoErrorCode\x12\x11\n\rUNKNOWN_ERROR\x10\x01\x12\x17\n\x13UNSUPPORTED_MESSAGE\x10\x02\x12\x13\n\x0fINVALID_REQUEST\x10\x03\x12\x11\n\rTIMEOUT_ERROR\x10\x05\x12\x14\n\x10\x45NTITY_NOT_FOUND\x10\x06\x12\x16\n\x12\x43\x41NT_ROUTE_REQUEST\x10\x07\x12\x12\n\x0e\x46RAME_TOO_LONG\x10\x08\x12\x11\n\rMARKET_CLOSED\x10\t\x12\x1b\n\x17\x43ONCURRENT_MODIFICATION\x10\n\x12\x18\n\x14\x42LOCKED_PAYLOAD_TYPE\x10\x0b\x42M\n(com.xtrader.protocol.proto.commons.modelB\x1c\x43ontainerCommonModelMessagesP\x01\xa0\x01\x01')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```

**Comment by marcus-santos** [comment]
Hi @Sergey-S-Lebedev !

The package service-identity is required for spotware-connect. It should have been installed when using pip.

Please, try reinstalling only the missing package: `pip install service-identity`

**Comment by Sergey-S-Lebedev** [comment]
Hi Marcus, naturally i installed service-identity via pip, it's not working in Ubuntu, but seems like in windows its okay, please inform community in which platform your package work

**Comment by Sergey-S-Lebedev** [comment]
rerards
Sergey
