### ISSUE TITLE
builtins.TypeError: Value must be iterable - when subscribing to "SubscribeSpotsReq"

### ISSUE THREAD

**Issue by rujaun** [marcus-santos/spotware_connect#3]
**Describe the bug**
When I try to emit `SubscribeSpotsReq` I get a `builtins.TypeError: Value must be iterable` error.

**To Reproduce**
`c.emit('SubscribeSpotsReq', ctidTraderAccountId=*redacted*, symbolId=5)`

Here is the full stacktrace:

```
Unhandled Error
Traceback (most recent call last):
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/twisted/protocols/basic.py", line 766, in dataReceived
    self.stringReceived(packet)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/spotware_connect/protocol.py", line 69, in stringReceived
    self.receive(msg)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/spotware_connect/client.py", line 28, in receive
    self.client.receive(message)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/spotware_connect/client.py", line 79, in receive
    self.exec_events(self.EVENT_MESSAGE_NAME, **kargs)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/spotware_connect/client.py", line 133, in exec_events
    f(*args, **kwargs)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/spotware_connect/client.py", line 115, in func_wrap
    func(*args, **kwargs)
  File "main.py", line 63, in on_trader_information
    c.emit('SubscribeSpotsReq', ctidTraderAccountId=20138441, symbolId=5)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/spotware_connect/client.py", line 83, in emit
    message = Protobuf.get(message, **params)
  File "/home/user/Fun/connect_bot/env/lib/python3.8/site-packages/spotware_connect/protobuf.py", line 36, in get
    return cls._protos[payload](**params)
builtins.TypeError: Value must be iterable
```

**Comment by rujaun** [comment]
Nevermind, issue resolved, `symbolId` should be in a list.

**Comment by hasanzad** [comment]
> Nevermind, issue resolved, `symbolId` should be in a list.

Hello, rujaun

I find spotware_connect 2 days ago. please advise how can I get the tick data and how to send order to the server. 
Actually I run the sample code which the Marcus put as sample.
tnx
